baseurl: "https://jakob.gillich.me/"
languageCode: "en-us"
title: "Jakob Gillich"
theme: "lanyon"
author:
  name: "Jakob Gillich"
permalinks:
  post = "/:title/"
params:
  tagline: "Personal blog"
  description: "Minimalist, developer."
  footer: "All content licensed under [CC BY 4.0](http://creativecommons.org/licenses/by/4.0/)."
  email: "mailto:jakob@gillich.me"
  github: "https://github.com/jgillich"
  stackoverflow: "http://stackoverflow.com/users/941764/jgillich"
menu:
  main:
    - identifier: "home"
      name: "home"
      url: "/"
      weight: 0
